# Generated by Django 5.2.10 on 2026-01-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apiendpoint',
            name='idx_api_endpoints_last_updat',
        ),
    ]
