# Generated by Django 5.2.10 on 2026-01-23 16:26

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_remove_apiendpoint_idx_api_endpoints_last_updat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hadith_number', models.PositiveIntegerField()),
                ('narrator', models.CharField(blank=True, max_length=255, null=True)),
                ('narrator_arabic', models.CharField(blank=True, max_length=500, null=True)),
                ('hadith_text_turkish', models.TextField(blank=True, null=True)),
                ('hadith_text_arabic', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='tr-ar', max_length=10)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hadiths',
                'ordering': ['hadith_number'],
                'indexes': [models.Index(fields=['hadith_number'], name='idx_hadith_number'), models.Index(fields=['language'], name='idx_hadith_language')],
            },
        ),
        migrations.CreateModel(
            name='HadithSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='chatApp.hadith')),
            ],
            options={
                'db_table': 'hadith_sources',
            },
        ),
        migrations.CreateModel(
            name='HadithEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hadith_number', models.PositiveIntegerField()),
                ('embedding_turkish', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('embedding_arabic', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hadith', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='chatApp.hadith')),
            ],
            options={
                'db_table': 'hadith_embeddings',
                'indexes': [models.Index(fields=['hadith_number'], name='idx_hadith_emb_number')],
            },
        ),
    ]
