# Generated by Django 5.2.10 on 2026-01-23 16:40

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_hadith_hadithsource_hadithembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadith',
            name='embedding',
        ),
        migrations.AddIndex(
            model_name='hadithembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_turkish'], m=16, name='idx_emb_turkish_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='hadithembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_arabic'], m=16, name='idx_emb_arabic_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
