# Generated by Django 5.2.10 on 2026-01-23 17:53

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_remove_hadith_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hadith_number', models.PositiveIntegerField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('language', models.CharField(choices=[('turkish', 'Turkish'), ('arabic', 'Arabic')], max_length=10)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='chatApp.hadith')),
            ],
            options={
                'db_table': 'hadith_chunk_embeddings',
                'ordering': ['hadith_number', 'language', 'chunk_index'],
                'indexes': [models.Index(fields=['hadith_number'], name='idx_chunk_hadith_number'), models.Index(fields=['language'], name='idx_chunk_language'), models.Index(fields=['hadith_number', 'language'], name='idx_chunk_hadith_lang'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_chunk_emb_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
