# Generated by Django 5.2.10 on 2026-01-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_hadithchunkembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='hadith_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithchunkembedding',
            name='hadith_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithembedding',
            name='hadith_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
