# Generated by Django 5.2.10 on 2026-01-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0006_alter_hadith_hadith_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='narrator_arabic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
