# Generated by Django 5.2.10 on 2026-01-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0007_alter_hadith_narrator_arabic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hadithchunkembedding',
            options={'ordering': ['hadith_number', 'chunk_type', 'chunk_index']},
        ),
        migrations.RemoveIndex(
            model_name='hadithchunkembedding',
            name='idx_chunk_language',
        ),
        migrations.RemoveIndex(
            model_name='hadithchunkembedding',
            name='idx_chunk_hadith_lang',
        ),
        migrations.RemoveField(
            model_name='hadithchunkembedding',
            name='language',
        ),
        migrations.AddField(
            model_name='hadith',
            name='embedding_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadith',
            name='potential_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadith',
            name='priority_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadithchunkembedding',
            name='chunk_type',
            field=models.CharField(choices=[('embedding_text', 'Embedding Text'), ('potential_question', 'Potential Question')], default='embedding_text', max_length=20),
        ),
        migrations.AlterField(
            model_name='hadithchunkembedding',
            name='chunk_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='hadithchunkembedding',
            index=models.Index(fields=['chunk_type'], name='idx_chunk_type'),
        ),
        migrations.AddIndex(
            model_name='hadithchunkembedding',
            index=models.Index(fields=['hadith_number', 'chunk_type'], name='idx_chunk_hadith_type'),
        ),
    ]
