# Generated by Django 5.2.10 on 2026-02-03 05:58

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0008_alter_hadithchunkembedding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiyerSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_id', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField()),
                ('pages', models.JSONField(blank=True, null=True)),
                ('summary_short', models.TextField(blank=True, null=True)),
                ('main_theme', models.CharField(blank=True, max_length=255, null=True)),
                ('potential_questions', models.JSONField(blank=True, null=True)),
                ('query_intents', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'siyer_sections',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['section_id'], name='idx_siyer_section_id'), models.Index(fields=['main_theme'], name='idx_siyer_main_theme')],
            },
        ),
        migrations.CreateModel(
            name='SiyerChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_code', models.CharField(max_length=50)),
                ('chunk_type', models.CharField(choices=[('summary', 'Summary'), ('potential_question', 'Potential Question'), ('query_intent', 'Query Intent')], max_length=20)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='chatApp.siyersection')),
            ],
            options={
                'db_table': 'siyer_chunk_embeddings',
                'ordering': ['section_code', 'chunk_type', 'chunk_index'],
                'indexes': [models.Index(fields=['section_code'], name='idx_siyer_chunk_sec_code'), models.Index(fields=['chunk_type'], name='idx_siyer_chunk_type'), models.Index(fields=['section_code', 'chunk_type'], name='idx_siyer_chunk_code_type'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_siyer_chunk_emb_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
