# Generated by Django 5.2.10 on 2026-04-01 18:26

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0009_siyersection_siyerchunkembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetvaQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fetva_id', models.CharField(max_length=50, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('paraphrase_questions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fetva_questions',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['fetva_id'], name='idx_fetva_id'), models.Index(fields=['subject'], name='idx_fetva_subject')],
            },
        ),
        migrations.CreateModel(
            name='FetvaChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fetva_code', models.CharField(max_length=50)),
                ('chunk_type', models.CharField(choices=[('question', 'Question'), ('paraphrase_question', 'Paraphrase Question')], max_length=20)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fetva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='chatApp.fetvaquestion')),
            ],
            options={
                'db_table': 'fetva_chunk_embeddings',
                'ordering': ['fetva_code', 'chunk_type', 'chunk_index'],
                'indexes': [models.Index(fields=['fetva_code'], name='idx_fetva_chunk_fetva_code'), models.Index(fields=['chunk_type'], name='idx_fetva_chunk_type'), models.Index(fields=['fetva_code', 'chunk_type'], name='idx_fetva_chunk_code_type'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_fetva_chunk_emb_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
